BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE sudenja CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE liste_sudaca CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE utakmice CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE sudjelovanja CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE natjecanja CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE sezone CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ekipe CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE klubovi CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE suci CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE uloge CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE rangovi CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE adrese CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE gradovi CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
