CREATE TABLE gradovi (
    oznaka_grada VARCHAR2(5) PRIMARY KEY,
    naziv VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE adrese (
    id_adrese NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oznaka_grada VARCHAR2(5) REFERENCES gradovi(oznaka_grada) NOT NULL,
    ulica VARCHAR2(100) NOT NULL,
    kucni_broj VARCHAR2(10) NOT NULL,
    postanski_broj VARCHAR2(5) NOT NULL
);

CREATE TABLE rangovi(
    naziv_ranga VARCHAR2(15) PRIMARY KEY
);

CREATE TABLE uloge(
    naziv_uloge VARCHAR2(15) PRIMARY KEY
);

CREATE TABLE suci (
    OIB CHAR(11) PRIMARY KEY CHECK (REGEXP_LIKE(OIB, '^[0-9]{11}$')),
    ime VARCHAR2(50) NOT NULL,
    prezime VARCHAR2(50) NOT NULL,
    datum_rodenja DATE NOT NULL,
    broj_telefona VARCHAR2(30) NOT NULL CHECK (REGEXP_LIKE(broj_telefona, '^[0-9+ \-()\/]+$')),
    id_adrese NUMBER REFERENCES adrese(id_adrese) NOT NULL,
    id_mjesta_rodenja NUMBER REFERENCES adrese(id_adrese) NOT NULL,
    naziv_ranga VARCHAR2(15) REFERENCES rangovi(naziv_ranga) NOT NULL
);

CREATE TABLE klubovi (
    id_kluba NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    naziv VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE ekipe (
    id_ekipe NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    naziv VARCHAR2(100) NOT NULL,
    konkurencija CHAR(1) CHECK (konkurencija IN ('M', 'Z')),
    id_kluba NUMBER REFERENCES klubovi(id_kluba) NOT NULL,
    CONSTRAINT uq_ekipe_klub_naziv UNIQUE (id_kluba, naziv)
);

CREATE TABLE sezone (
    oznaka_sezone VARCHAR2(20) PRIMARY KEY,
    datum_pocetka DATE NOT NULL,
    datum_zavrsetka DATE,
    CONSTRAINT chk_sezone_datum CHECK (datum_zavrsetka IS NULL OR datum_zavrsetka > datum_pocetka)
);

CREATE TABLE natjecanja (
    id_natjecanja NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    naziv VARCHAR2(150) NOT NULL,
    konkurencija CHAR(1) NOT NULL CHECK (konkurencija IN ('M', 'Z')),
    oznaka_sezone VARCHAR2(20) REFERENCES sezone(oznaka_sezone) NOT NULL,
    naziv_minimalnog_ranga VARCHAR2(15) REFERENCES rangovi(naziv_ranga) NOT NULL,
    CONSTRAINT uq_natjecanja_sezona_naziv UNIQUE (oznaka_sezone, naziv)
);

CREATE TABLE sudjelovanja(
    id_ekipe NUMBER NOT NULL REFERENCES ekipe(id_ekipe) ON DELETE CASCADE,
    id_natjecanja NUMBER NOT NULL REFERENCES natjecanja(id_natjecanja) ON DELETE CASCADE,
    PRIMARY KEY(id_ekipe, id_natjecanja)
);

CREATE TABLE utakmice (
    id_utakmice NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datum DATE NOT NULL,
    vrijeme_pocetka TIMESTAMP NOT NULL,
    vrijeme_zavrsetka TIMESTAMP,
    rezultat_domacin NUMBER DEFAULT 0 NOT NULL CHECK (rezultat_domacin >= 0),
    rezultat_gost NUMBER DEFAULT 0 NOT NULL CHECK (rezultat_gost >= 0),
    id_natjecanja NUMBER NOT NULL CONSTRAINT fk_utakmice_natjecanja REFERENCES natjecanja(id_natjecanja),
    id_domacin NUMBER NOT NULL CONSTRAINT fk_utakmice_domacin REFERENCES ekipe(id_ekipe),
    id_gost NUMBER NOT NULL CONSTRAINT fk_utakmice_gost REFERENCES ekipe(id_ekipe),
    CONSTRAINT chk_utakmice_domacin_gost CHECK (id_domacin <> id_gost),
    CONSTRAINT chk_utakmice_vrijeme CHECK (vrijeme_zavrsetka IS NULL OR vrijeme_zavrsetka > vrijeme_pocetka)
);

CREATE TABLE liste_sudaca (
    id_natjecanja NUMBER NOT NULL REFERENCES natjecanja(id_natjecanja) ON DELETE CASCADE,
    OIB CHAR(11) NOT NULL REFERENCES suci(OIB) ON DELETE CASCADE,
    PRIMARY KEY(id_natjecanja, OIB)
);


CREATE TABLE sudenja (
    id_utakmice NUMBER NOT NULL REFERENCES utakmice(id_utakmice) ON DELETE CASCADE,
    OIB CHAR(11) NOT NULL REFERENCES suci(OIB) ON DELETE CASCADE,
    naziv_uloge VARCHAR2(15) NOT NULL REFERENCES uloge(naziv_uloge),
    ocjena NUMBER NOT NULL CHECK (ocjena BETWEEN 1 AND 5),
    PRIMARY KEY(id_utakmice, OIB, naziv_uloge)
);